# Generated by Django 2.1.5 on 2019-12-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191215_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
