# Generated by Django 2.1.5 on 2019-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191218_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
